# Generated by Django 3.0.8 on 2020-07-24 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_application_permission_staffhistory_studenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='permission',
            name='done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='application',
            name='attached_file',
            field=models.FileField(default='defaultFile.png', upload_to='attached_files'),
        ),
    ]
