# Generated by Django 3.0.8 on 2020-07-24 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20200724_1830'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='status',
            field=models.TextField(default=''),
        ),
    ]
