# Generated by Django 3.0.8 on 2020-07-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_permission_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
