# Generated by Django 3.0.8 on 2020-07-24 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20200724_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.RemoveField(
            model_name='staffhistory',
            name='author',
        ),
        migrations.DeleteModel(
            name='StudentHistory',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='StaffHistory',
        ),
    ]
